---
title: "ann"
author: "Daniel Gao, Aarnav Putta"
date: "2024-11-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Front Matter
```{r}
library(nnet)
library(tidyverse)
```


### Data
```{r}
test = read.csv("./test_timeseries.csv/test_timeseries.csv")
train = read.csv("./train_timeseries.csv/train_timeseries.csv") 
val = read.csv("./validation_timeseries.csv/validation_timeseries.csv") 
soil = read.csv("./soil_data.csv")
```


```{r}
#Combine test, train, val - will be used later in the code block
Drought <-
  test %>%
  bind_rows(train) %>%
  bind_rows(val)

DroughtED <-
  Drought %>%
  filter(score != 0)

#scale the data 
DroughtED[,3:20] <- scale(DroughtED[,3:20], center = TRUE, scale = TRUE)

cat("Results from removing the null values\n", 
    "Before:", nrow(Drought), "\n",
    "After:", nrow(DroughtED),"\n",
    "Total Removed:", nrow(Drought) - nrow(DroughtED),"\n",
    "Percentage Removed:",1-nrow(DroughtED)/nrow(Drought) )
```
### Splitting Data 
```{r}
# Train/Validation split
set.seed(315)
trainInd <- sample(1:nrow(DroughtED), floor(0.85*nrow(DroughtED)))
set.seed(NULL)

train <- DroughtED[trainInd, ]
val <- DroughtED[-trainInd, ]

train$score <- as.integer(train$score)
val$score <- as.integer(val$score)

train$score <- as.factor((train$score))
val$score <- as.factor(val$score)

```

```{r}
#memory save
Drought = 0
DroughtED = 0
test = 0
trainInd = 0 
```

#Understand the type
```{r}
# Train an ANN with one hidden layer
model <- nnet(score ~ PRECTOT+PS+QV2M+T2M+T2MDEW+T2MWET+T2M_MAX+T2M_MIN+T2M_RANGE+TS+WS10M+WS10M_MAX+WS10M_MIN+WS10M_RANGE+WS50M+WS50M_MAX+WS50M_MIN+WS50M_RANGE, data = train, size = 5, linout = FALSE)

predictions <- predict(model, newdata = val, type = "class")

accuracy <- sum(predictions == val$score) / nrow(val)

cat("Accuracy:", round(accuracy, 2))
```



