---
title: "midterm_analysis"
author: "Daniel Gao"
date: "2024-10-27"
output: html_document
---


### Front Matter
```{r}
remove(list = ls())

#Add libraries as needed
library(tidyverse)
```

### Data
```{r}
test = read.csv("./test_timeseries.csv/test_timeseries.csv") 
#train = read.csv("./train_timeseries.csv/train_timeseries.csv") 
val = read.csv("./validation_timeseries.csv/validation_timeseries.csv") 
soil = read.csv("./soil_data.csv")
head(test)
head(val)
head(soil)
```
### Combining Datasets
```{r}
droughtdf<-
  test%>%
  bind_rows(val)
head(droughtdf)
```
### Simple Explorations
```{r}
#number of variables 
num1 <- ncol(droughtdf) 
num2 <- ncol(soil)
num1
num2
```


```{r}
names(droughtdf)
names(soil)
```


```{r}
#null value checker
colSums(is.na(droughtdf))
colSums(is.na(soil))
```


```{r}
# PRECTOT - Total Precipitation
ggplot(data=droughtdf, mapping=aes(x=PRECTOT)) +
  geom_density()

# PS - Surface Pressure
ggplot(data=droughtdf, mapping=aes(x=PS)) +
  geom_density()

# QV2M - Specific Humidity at 2 meters
ggplot(data=droughtdf, mapping=aes(x=QV2M)) +
  geom_density()
```

### DroughDF fips
```{r}
#location fips
droughtdf %>%
  group_by(fips) %>%
  summarize(count = n()) %>%
  head() 

droughtdf %>%
  group_by(fips) %>%
  summarize(count = n()) %>%
  tail() 
```
### Soil fips
```{r}
soil %>%
  group_by(fips) %>%
  summarize(count = n()) %>%
  head() 

soil %>%
  group_by(fips) %>%
  summarize(count = n()) %>%
  tail() 
```
### PRECTOT and FIPS
```{r}
droughtdf %>%
  group_by(fips,PRECTOT) %>%
  summarize(n = n()) %>%
  arrange(desc(PRECTOT)) %>%
  tail()

```




